spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    show_sql: true
  profiles:
    active: local
logging:
 level:
  org:
   hibernate:
    type:
     descriptor:
      sql: trace

